language: node_js
branches:
  except:
    - gh-pages
sudo: false
node_js:
  - "stable"
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run build
  - npm test
notifications:
  email:
    on_success: change
    on_failure: change
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  on:
    branch: master